### ISSUE TITLE
omtd-simple-workflows-sshner fail to constructed

### ISSUE THREAD

**Issue by JKChang2015** [galanisd/omtd-simple-workflows#3]
Hi,

I'm trying to construct the project by maven. Following dependencies are missing:
//------------------------------------------------------------------------
Building omtd-simple-workflows-sshner 0.0.1-SNAPSHOT
//------------------------------------------------------------------------
The POM for eu.openminted.uc-tdm-socialsciences:ss-io-pdf:jar:1.0.1-SNAPSHOT is missing, no dependency information available

The POM for eu.openminted.uc-tdm-socialsciences:ss-module-ner:jar:1.0.1-SNAPSHOT is missing, no dependency information available

**Comment by maxxkia** [comment]
@gkirtzou @JKChang2015  These dependencies are located in openminted maven snapshots repository. This repository `https://repo.openminted.eu/content/repositories/snapshots` should be added to the pom file.

**Comment by maxxkia** [comment]
```
<repository>
	<id>omtd-snapshots</id>
	<name>omtd-snapshots</name>
	<url>https://repo.openminted.eu/content/repositories/snapshots</url>
	<releases>
		<enabled>false</enabled>
	</releases>
	<snapshots>
		<enabled>true</enabled>
	</snapshots>
</repository>
```

**Comment by galanisd** [comment]
Did you follow the instructions in
https://github.com/galanisd/omtd-simple-workflows/#installation
?

You have to run ./installProjectsDepedencies.sh before mvn clean install.
Among other things it downloads a specific version of https://github.com/openminted/uc-tdm-socialsciences.git and builds it.

**Comment by JKChang2015** [comment]
@maxxkia @galanisd Thank you very much, the problem has been solved.
