### ISSUE TITLE
XMI file parsing tool

### ISSUE THREAD

**Issue by JKChang2015** [galanisd/omtd-simple-workflows#4]
Hello,
I would like to parse and visualise the text mining result (XMI file) for CHEBI workflow. Could you please let me know which tool / package can be used for this purpose? Thank you.

**Comment by galanisd** [comment]
Hello,

This repo was created in the context of OpenMinTeD project. The output you have 
is from the CHEBI workflow which has been deployed as a web service @ Univ. of Manchester (UNIMAN).  I think that you should ask UNIMAN for this ...I will fwd you message to them. You probably need  the respective UIMA typesystem and libraries etc.

**Comment by nguyennth** [comment]
Hello,

We're sorry that the XMI parser component hasn't been available in OpenMinTeD yet. In the meantime, you probably want to try UIMAFit XMI Reader: http://ctakes.apache.org/apidocs/4.0.0/org/apache/ctakes/dependency/parser/ae/util/XMIReader.html 

Hope this helps.

**Comment by JKChang2015** [comment]
Hello, 

@stampit12 Thank you. Is it possible to visualise the XMI file in brat system?

**Comment by nguyennth** [comment]
Hi,

I'm afraid brat can't read XMI, please check brat file format here: http://brat.nlplab.org/standoff.html 
So, if you can convert the XMI result into the standoff format, brat can visualise your result.

**Comment by JKChang2015** [comment]
OK，Thank you for your help.
